from PIL import Image 
def main():
    img = Image.open("han.jpeg")
    newsize = (80,40)
    im1 = img.resize(newsize)
    image = im1.convert("L")
    image.save("grayscle.jpg")
    width,height = image.size
    x = width
    y = height
    for i in range(y):
        row = []
        for j in range(x):
            pixel = image.getpixel((j, i))

            if pixel <= 3:
                char = "@"
            elif pixel <= 7:
                char = "#"
            elif pixel <= 11:
                char = "8"
            elif pixel <= 15:
                char = "&"
            elif pixel <= 19:
                char = "W"
            elif pixel <= 22:
                char = "M"
            elif pixel <= 26:
                char = "$"
            elif pixel <= 30:
                char = "B"
            elif pixel <= 34:
                char = "%"
            elif pixel <= 38:
                char = "*"
            elif pixel <= 41:
                char = "o"
            elif pixel <= 45:
                char = "a"
            elif pixel <= 49:
                char = "h"
            elif pixel <= 53:
                char = "k"
            elif pixel <= 57:
                char = "b"
            elif pixel <= 60:
                char = "d"
            elif pixel <= 64:
                char = "p"
            elif pixel <= 68:
                char = "q"
            elif pixel <= 72:
                char = "w"
            elif pixel <= 76:
                char = "m"
            elif pixel <= 79:
                char = "Z"
            elif pixel <= 83:
                char = "O"
            elif pixel <= 87:
                char = "0"
            elif pixel <= 91:
                char = "Q"
            elif pixel <= 95:
                char = "L"
            elif pixel <= 98:
                char = "C"
            elif pixel <= 102:
                char = "J"
            elif pixel <= 106:
                char = "U"
            elif pixel <= 110:
                char = "Y"
            elif pixel <= 114:
                char = "X"
            elif pixel <= 117:
                char = "z"
            elif pixel <= 121:
                char = "c"
            elif pixel <= 125:
                char = "v"
            elif pixel <= 129:
                char = "u"
            elif pixel <= 133:
                char = "n"
            elif pixel <= 137:
                char = "x"
            elif pixel <= 140:
                char = "r"
            elif pixel <= 144:
                char = "j"
            elif pixel <= 148:
                char = "f"
            elif pixel <= 152:
                char = "t"
            elif pixel <= 156:
                char = "/"
            elif pixel <= 159:
                char = "|"
            elif pixel <= 163:
                char = "\\"
            elif pixel <= 167:
                char = "("
            elif pixel <= 171:
                char = ")"
            elif pixel <= 175:
                char = "1"
            elif pixel <= 178:
                char = "{"
            elif pixel <= 182:
                char = "}"
            elif pixel <= 186:
                char = "["
            elif pixel <= 190:
                char = "]"
            elif pixel <= 194:
                char = "?"
            elif pixel <= 197:
                char = "-"
            elif pixel <= 201:
                char = "_"
            elif pixel <= 205:
                char = "+"
            elif pixel <= 209:
                char = "~"
            elif pixel <= 213:
                char = "<"
            elif pixel <= 216:
                char = ">"
            elif pixel <= 220:
                char = "i"
            elif pixel <= 224:
                char = "!"
            elif pixel <= 228:
                char = "l"
            elif pixel <= 232:
                char = "I"
            elif pixel <= 235:
                char = ";"
            elif pixel <= 239:
                char = ":"
            elif pixel <= 243:
                char = ","
            elif pixel <= 247:
                char = "^"
            elif pixel <= 251:
                char = "`"
            elif pixel <= 254:
                char = "'"
            else:
                char = " "

            row.append(char)
        print("".join(row))
if __name__ == "__main__":
    main()
